import "./globals.css"

import { Toaster } from "@/components/ui/toaster"
import Provider from "@/components/Provider"

export const metadata = {
  title: "Polymath Chatbot",
  description: "Generated by Polymath",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Provider>
          {children}
          <Toaster />
        </Provider>
      </body>
    </html>
  )
}
